version: '3.7'
services:


  influxdb:
    # Use the appropriate Docker Hub repository (https://hub.docker.com/_/influxdb) for your CPU architecture.
    image: arm64v8/influxdb:latest
    env_file:
      - influxdb.env
    volumes:
      - influxdbv:/var/lib/influxdb2:rw
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
      - ./influxdb/templates:/templates
    ports:
      - 8086:8086
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 10s
      timeout: 30s
      retries: 5
    restart: always


  telegraf:
    # Use the appropriate Docker Hub repository (https://hub.docker.com/_/telegraf/) for your CPU architecture.
    image: arm64v8/telegraf:latest
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxdb.env
    restart: always
    # Further information: "Running InfluxDB 2.0 and Telegraf Using Docker"
    # (https://www.influxdata.com/blog/running-influxdb-2-0-and-telegraf-using-docker/)
    # Further information: "Install Grafana/InfluxDB/Telegraf using Docker Compose"
    # (https://dev.to/project42/install-grafana-influxdb-telegraf-using-docker-compose-56e9)
    

  python:
    build: ./python
    depends_on:
      influxdb:
        condition: service_healthy
    # Provides access to the sensor.
    # Further information: "Docker Access to Raspberry Pi GPIO Pins"
    # (https://stackoverflow.com/questions/30059784/docker-access-to-raspberry-pi-gpio-pins)
    devices:
      - /dev/gpiomem:/dev/gpiomem
    restart: always


volumes:
  influxdbv: