version: '3.7'
services:

  influxdb:
    image: influxdb:latest
    env_file:
      - influxdb.env
    volumes:
      - influxdbv:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    restart: always

  telegraf:
    image: telegraf:latest
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxdb.env
    restart: always

  python:
    build: ./python
    depends_on:
      telegraf:
        condition: service_started
    devices:
      - /dev/gpiomem:/dev/gpiomem
    # privileged: true
    # volumes:
    #   - /sys/class/gpio:/sys/class/gpio
    #   - /sys:/sys

    # privileged: true
    # devices:
    #  - /dev/gpiomem
    # working_dir: /usr/src/app
    # volumes:
    #   - ./python:/usr/src/app        

networks:
  monitoring:

volumes:
  influxdbv:

# https://docs.docker.com/compose/env-file/
# https://hub.docker.com/_/telegraf/
# https://hub.docker.com/_/influxdb
# https://hub.docker.com/_/python
# https://www.influxdata.com/blog/running-influxdb-2-0-and-telegraf-using-docker/
# https://dev.to/project42/install-grafana-influxdb-telegraf-using-docker-compose-56e9
# https://stackoverflow.com/questions/30059784/docker-access-to-raspberry-pi-gpio-pins
# https://stackoverflow.com/questions/71060072/docker-compose-depends-on-with-condition-invalid-type-should-be-an-array

# docker compose up --remove-orphans
# docker compose up -d --build --remove-orphans
# docker-compose build --no-cache
# docker-compose down --volumes

# user: pi
# password: raspberry