version: '3.7'
services:


  influxdb:
    # Use the appropriate Docker Hub repository (https://hub.docker.com/_/influxdb) for your CPU architecture.
    image: arm64v8/influxdb:latest
    env_file:
      - .env
    volumes:
      - influxdbv:/var/lib/influxdb2:rw
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
      - ./influxdb/templates:/templates
    ports:
      - ${DOCKER_INFLUXDB_PORT}:${DOCKER_INFLUXDB_PORT}
    # Periodic check of the health status of the Docker container to ensure accessibility.
    healthcheck:
      test: "curl -f http://localhost:${DOCKER_INFLUXDB_PORT}/ping"
      interval: 10s
      timeout: 30s
      retries: 5
    restart: always


  python:
    build: ./python
    env_file:
      - .env
      - py.env
    depends_on:
      influxdb:
        condition: service_healthy
    # Provides access to the sensor.
    # Further information: "Docker Access to Raspberry Pi GPIO Pins"
    # https://stackoverflow.com/questions/30059784/docker-access-to-raspberry-pi-gpio-pins
    devices:
      - /dev/gpiomem:/dev/gpiomem
    restart: always


volumes:
  influxdbv: